services:
  - type: web
    name: intelli-migrate-api
    runtime: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r backend/requirements.txt && pip install -r backend/requirements-ml.txt
    startCommand: gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
